server:
  port: ${PORT:0}
spring:
  application:
     name: pod-ws
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://129.154.196.75:3306/test
    username: test
    password: 1234

eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8010/eureka


mybatis:
  type-aliases-package: com.k8smanager.pod.data
  mapper-locations: mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
